### PR TITLE
Fix tag changes pagination not preserving added query param

### LINKED ISSUE #9: Viewing tag history removed only or added only doesn’t work with multi page tag history
**Describe the bug**
When viewing tag history on an image and using removed only or added only going to a second page of it will change it back to all. This happens on both Derpibooru and Furbooru

**To Reproduce**
1. Go to an image with enough tag history for multi pages, [This one is a good example](https://furbooru.org/images/5105?sd=desc&sf=tag_count&q=safe)
2. Go to that images tag history. [Direct link to the above images tag history](https://furbooru.org/images/5105/tag_changes)
3. Select removed or added only then click next. (Selecting removed on this image makes it much easier to see the bug)
4.  On the second page it will be back to showing all tags rather than what you have selected.

**Expected behavior**
Having the tag history set to removed only/added only should stay on removed/added only when going to another page of that images tag history.

**Smartphone (please complete the following information):** 
 - Device: iPad 5th gen
 - OS: iOS 13.5.1
 - Browser: Safari
 - Version: 13.1

### PR DESCRIPTION
**Pull request by SeinopSys**
Closes #9

### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [x] I understand all of the above

---

Fix for #9

### CODE REVIEW

**Comment by SeinopSys** [comment]
Looks like this will be fixed by https://github.com/philomena-dev/philomena/commit/5532ea4dec349563c1260823bce6709fc299c8e8 whenever it's merged

**Comment by liamwhite** [comment]
It wasn't, but I [pulled over](https://github.com/philomena-dev/philomena/commits/2c121c80c8718788b7c66c91a1c735e368a95b9d) your changes anyway.

**Comment by SeinopSys** [comment]
@liamwhite Oh, it looked like the same plug could be used there as well instead

**Comment by liamwhite** [comment]
No, it was a fix for a different issue.

**Pull request closed without merging**
