### PR TITLE
Block more erroneous tags

### PR DESCRIPTION
**Pull request by CrystalSplitter**
### Important note
If the changes you are making are not specific to Furbooru, please send your pull request to the [upstream repository](https://github.com/philomena-dev/philomena) instead.
- [x] My changes are specific to Furbooru

### Before you begin

* I understand my contributions may be rejected for any reason
* I understand my contributions are for the benefit of the Philomena software
* I understand my contributions are licensed under the GNU AGPLv3

- [x] I understand all of the above

---

Add more tags to the tag.json blacklist, as request by Pharynx. Also sort the tags
alphabetically. These tag edits are specific to Furbooru, and may not make
sense on Philomena upstream.

### CODE REVIEW

**Comment by Meow** [comment]
consider also adding these:
- furryart
- furryartwork
- furryartist
- furrynsfw
- furryanthro
- nsfwart
- nsfwartist
- nsfwartwork
- nsfwanthro
- anthrooc
- anthrofurry
- anthroart
- anthronsfw

**Comment by Meow** [comment]
also
- furry artist
- furry community
- furry art
- furry cute
- furry anthro
- furry oc
- furry character
- furry fandom
- furries
- fandom
- cute furry
- cute art
- cute artwork
- anthroartist
- anthro art
- anthro artist
- anthro cute
- anthro nsfw
- nsfw anthro

and basically everything else i suggested before, but with a space in between words

**Comment by CrystalSplitter** [comment]
Want to just make these  edits inline, or would you rather I post an updated version? It's not an issue, just not sure the workflow you prefer.

**Comment by Meow** [comment]
just updating this pull request is fine

**Comment by CrystalSplitter** [comment]
Done.

**Pull request merged**
